language: python
python:
  - 3.9

install:
  - curl -OsSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - export PATH=$PATH:~/.poetry/bin
  - poetry install

script:
  - poetry run foliant make site -p docs

deploy:
  - provider: script
    script: poetry publish --build --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD"
    on:
      tags: true
  - provider: pages
    local-dir: sloth-ci-docs.mkdocs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: develop

