__title__ = 'sloth-ci'
__description__ = 'Simple app for automatization of everything'
__long_description__ = 'Sloth CI: CI for Humans. A simple and extendable automatization app.'
__version__ = '2.0.1'
__author__ = 'Konstantin Molchanov'
__author_email__ = 'moigagoo@live.com'
__license__ = 'MIT'