listen_point: listen/myapp

provider:
    github:
        owner: username
        repo: repo
        branches:
            - dev
            - staging

actions:
    - touch {filename}
    - echo "The branch is {branch}" >> {filename}

params:
    filename: myfile.txt

work_dir: ~/apps/myapp

exec_timeout: 5

stop_on_first_fail: true

extensions:
    debug_logs:
        module: file_logs
        path: /var/log/myapp/
        filename: myapp_debug.log
        level: DEBUG
