repo_url: https://github.com/sloth-ci/sloth-ci
edit_uri: edit/develop/docs/src/

theme:
  name: material
  palette:
    primary: red
    accent: green
  font:
    text: PT Sans
    code: PT Mono
  logo: assets/sloth.png
  favicon: assets/favicon.ico

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition
  - def_list
  - footnotes

copyright: >
  <p>Created by <a href="https://github.com/moigagoo/">Constantine Molchanov</a>
  using <a href="https://foliant.rocks">Foliant</a>.</p>

