host: 0.0.0.0
port: 8080

auth: # or api_auth
    login: admin
    password: password

paths:
    access_log: /usr/log/sloth-ci/access.log
    error_log: /usr/log/sloth-ci/error.log

    db: /etc/sloth-ci/sloth.db

    configs:
        - /etc/conf.d/sloth-ci/*.yml

extensions:
    hide-from-robots:
        module: robots_txt

daemon: true
