name: Deploy Docs

on:
    push:
      branches:
        - develop

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run:
          - curl -OsSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
          - python install-poetry.py --preview -y
          - export PATH=$PATH:~/.poetry/bin
          - poetry install

      - name: Docs
        run: poetry run foliant make site -p docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sloth-ci-docs.mkdocs

